From bugzilla-daemon at main.slony.info  Wed Feb 11 07:42:48 2015
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 11 Feb 2015 07:42:48 -0800 (PST)
Subject: [Slony1-bugs] [Bug 358] New: The slonik_execute_script generates
 the command with the set on 2.2.4
Message-ID: <bug-358-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=358

           Summary: The slonik_execute_script generates the command with
                    the set on 2.2.4
           Product: Slony-I
           Version: 2.0
          Platform: All
        OS/Version: Linux
            Status: NEW
          Severity: trivial
          Priority: low
         Component: altperl
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: federico at brandwatch.com
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


Created an attachment (id=212)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=212)
slonik_execute_script patch for 2.2.4

Not sure if this is the correct place to report, anyway I've found a minor
issue with the slonik_execute_script after upgrading to slony 2.2.4.

The script generates the EXECUTE SCRIPT specifying the set id which is no
longer in use for the 2.2.4.
The attached patch makes the perl script's output compatible with the 2.2.4.

The changes are basically.

1) replace the set id with the eventnode id
2) remove the set id from the output.

Thanks

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Feb 11 07:47:24 2015
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 11 Feb 2015 07:47:24 -0800 (PST)
Subject: [Slony1-bugs] [Bug 358] The slonik_execute_script includes the set
 id on slony 2.2.4
In-Reply-To: <bug-358-4@http.www.slony.info/bugzilla/>
References: <bug-358-4@http.www.slony.info/bugzilla/>
Message-ID: <20150211154724.4CE722916EC@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=358

Federico Campoli <federico at brandwatch.com> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
            Summary|The slonik_execute_script   |The slonik_execute_script
                   |generates the command with  |includes the set id on
                   |the set on 2.2.4            |slony 2.2.4

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Feb 11 12:01:46 2015
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 11 Feb 2015 12:01:46 -0800 (PST)
Subject: [Slony1-bugs] [Bug 358] The slonik_execute_script includes the set
 id on slony 2.2.4
In-Reply-To: <bug-358-4@http.www.slony.info/bugzilla/>
References: <bug-358-4@http.www.slony.info/bugzilla/>
Message-ID: <20150211200146.652A129199F@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=358

Christopher Browne <cbbrowne at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         AssignedTo|slony1-bugs at lists.slony.inf |rnancy at afilias.info
                   |o                           |
             Status|NEW                         |ASSIGNED

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Fri Feb 13 10:45:58 2015
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Fri, 13 Feb 2015 10:45:58 -0800 (PST)
Subject: [Slony1-bugs] =?utf-8?q?=5BBug_346=5D_error=3A__unknown_type_name?=
 =?utf-8?b?IOKAmGluc2VydOKAmQ==?=
In-Reply-To: <bug-346-4@http.www.slony.info/bugzilla/>
References: <bug-346-4@http.www.slony.info/bugzilla/>
Message-ID: <20150213184558.BB6B22919F3@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=346

Steve Singer <ssinger at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         Resolution|                            |WONTFIX
             Status|NEW                         |RESOLVED

--- Comment #2 from Steve Singer <ssinger at ca.afilias.info> 2015-02-13 10:45:58 PST ---
Slony 1-1.2.23 is no longer supported.
If you can reproduce this error in slony 2.2.x you can re-open the bug and we
can look at it.

Also, I recommend you run configure as
./configure --with-pgconfigdir=//usr/lib/postgresql/8.3/bin

(or whatever the path is) instead of with with-pgincludedir this might fix your
issue.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

