From ragavendra.dba at gmail.com  Mon Jul  1 04:42:30 2013
From: ragavendra.dba at gmail.com (Raghav)
Date: Mon, 1 Jul 2013 17:12:30 +0530
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
Message-ID: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>

Hi,

Firstly, many thanks for new release of Slony 2.2Beta.

I am testing the new beta, I observed few things and want to know from here
if am missing anything.

1. Executing any DDL on replicating table will crash the replication and
error out as below:

2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: "insert into
"public"."stest" ("id","name") values ('1','asdf');
" ERROR:  column "name" of relation "stest" does not exist
LINE 1: insert into "public"."stest" ("id","name") values ('1','asdf...
2013-06-15 12:31:17 IST DEBUG2 remoteWorkerThread_1: cleanup
2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: SYNC aborted

But the same is not happening in BETA (I have executed ALTER TABLE
command). Am I missing anything here ?

2. Does slony archives(slon -a) capture DDL events in .sql file ?


-- 

Regards
Raghav
Blog: htt://raghavt.blogspot.com/
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130701/7579cc33/attachment.html 

From ssinger at ca.afilias.info  Mon Jul  1 09:37:47 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Mon, 01 Jul 2013 12:37:47 -0400
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
In-Reply-To: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
References: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
Message-ID: <51D1B05B.8010609@ca.afilias.info>

On 07/01/2013 07:42 AM, Raghav wrote:
> Hi,
>
> Firstly, many thanks for new release of Slony 2.2Beta.

Thanks for trying to test the beta.

>
> I am testing the new beta, I observed few things and want to know from
> here if am missing anything.
>
> 1. Executing any DDL on replicating table will crash the replication and
> error out as below:
>
> 2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: "insert into
> "public"."stest" ("id","name") values ('1','asdf');
> " ERROR:  column "name" of relation "stest" does not exist

What does your table stest look like on the replica?  Does it have a 
column "name" ?

What DDL did you execute and in what order?  If you are adding or 
dropping the "name" column then this sounds like a bug, but more details 
so we can reproduce this would be helpful.

> LINE 1: insert into "public"."stest" ("id","name") values ('1','asdf...
> 2013-06-15 12:31:17 IST DEBUG2 remoteWorkerThread_1: cleanup
> 2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: SYNC aborted
>
> But the same is not happening in BETA (I have executed ALTER TABLE
> command). Am I missing anything here ?
>
> 2. Does slony archives(slon -a) capture DDL events in .sql file ?
>
>

Looking at the code, I *think* the DDL events will show up in the the 
.sql files as part of the copy stream, but the apply trigger the 
slony1_dump.sh installs on the log shipping node won't process them. 
This sounds like a bug/oversight.



> --
>
> Regards
> Raghav
> Blog: htt://raghavt.blogspot.com/ <http://raghavt.blogspot.com/>
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general


